apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Application Runtime, Monitoring, Security
    certified: "false"
    containerImage: registry.redhat.io/dvo/deployment-validation-rhel8-operator@sha256:74728420bb74a5a9a8040b48413da48f506e42b333df53c2067f53f614a2342d
    createdAt: 2024-11-27T00:00:00Z
    description: The deployment validation operator
    operators.openshift.io/valid-subscription: "[\"OpenShift Container Platform\", \"OpenShift Platform Plus\"]"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0+git
    operators.operatorframework.io/project_layout: unknown
    repository: https://github.com/app-sre/deployment-validation-operator
    support: Best Effort
    ignore-check.kube-linter.io/minimum-three-replicas: "This deployment uses 1 pod as currently replicating does not replicate metric data causing installation issues"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
  name: deployment-validation-operator.v0.7.13
spec:
  description: |
    The Deployment Validation Operator (DVO) checks deployments and other resources against a curated collection of best practices.
    These best practices focus mainly on ensuring that the applications are fault-tolerant. DVO reports failed validations via Prometheus metrics.
    If the best-practice check has failed, the metrics will report `1`.
  displayName: Deployment Validation Operator
  icon:
    - base64data: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4="
      mediatype: "image/svg+xml"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
        serviceAccountName: deployment-validation-operator
      deployments:
      - label:
          app: deployment-validation-operator
        name: deployment-validation-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment-validation-operator
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
            type: RollingUpdate
          template:
            metadata:
              labels:
                app: deployment-validation-operator
                name: deployment-validation-operator
            spec:
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - deployment-validation-operator
                      topologyKey: kubernetes.io/hostname
                    weight: 100
              containers:
              - args:
                - --config /config/deployment-validation-operator-config.yaml
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: deployment-validation-operator
                - name: NAMESPACE_IGNORE_PATTERN
                  value: "^(openshift.*|kube-.*|open-cluster-management-.*|default|dedicated-admin|redhat-.*|acm|addon-dba-operator|codeready-.*|prow)$"
                - name: RESOURCES_PER_LIST_QUERY
                  value: "5"
                - name: VALIDATION_CHECK_INTERVAL
                  value: "2m"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: registry.redhat.io/dvo/deployment-validation-rhel8-operator@sha256:74728420bb74a5a9a8040b48413da48f506e42b333df53c2067f53f614a2342d
                imagePullPolicy: Always
                name: deployment-validation-operator
                ports:
                - containerPort: 8383
                  name: http-metrics
                  protocol: TCP
                resources:
                  limits:
                    memory: 400Mi
                  requests:
                    cpu: 50m
                    memory: 200Mi
                securityContext:
                  readOnlyRootFilesystem: true
                volumeMounts:
                - name: dvo-config
                  mountPath: /config
              restartPolicy: Always
              serviceAccountName: deployment-validation-operator
              terminationGracePeriodSeconds: 30
              volumes:
              - name: dvo-config
                configMap:
                  name: deployment-validation-operator-config
                  optional: true
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          verbs:
          - get
          - create
          - list
          - delete
          - update
          - watch
          - patch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - '*'
        serviceAccountName: deployment-validation-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: AllNamespaces
  - supported: false
    type: MultiNamespace
  keywords:
  - dvo
  labels:
    alm-owner-dvo: deployment-validation-operator
    operated-by: deployment-validation-operator
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
  links:
  - name: repository
    url: https://github.com/app-sre/deployment-validation-operator
  - name: containerImage
    url: registry.redhat.io/dvo/deployment-validation-rhel8-operator@sha256:74728420bb74a5a9a8040b48413da48f506e42b333df53c2067f53f614a2342d
  maintainers:
  - name: Red Hat
    email: dvo-owners@redhat.com
  maturity: alpha
  provider:
    name: Red Hat
  selector:
    matchLabels:
      alm-owner-dvo: deployment-validation-operator
      operated-by: deployment-validation-operator
  replaces: deployment-validation-operator.v0.7.12
  skipRange: ">=0.0.10 <0.7.5"
  version: 0.7.13
