---
apiVersion: v1
kind: Template
metadata:
  name: deployment-validation-operator
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: ${SOURCE}
  spec:
    sourceType: grpc
    grpcPodConfig:
      securityContextConfig: restricted
    image: ${IMAGE}:${IMAGE_TAG}
    displayName: Deployment Validation Operator
    publisher: ${CATALOG_PUBLISHER}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: deployment-validation-operator
  spec:
    channel: ${CHANNEL}
    name: deployment-validation-operator
    source: ${SOURCE}
    sourceNamespace: ${SOURCE_NAMESPACE}
    config:
      env:
      - name: NAMESPACE_IGNORE_PATTERN
        value: ${NAMESPACE_IGNORE_PATTERN}
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: deployment-validation-operator
    namespace: ${NAMESPACE}
  spec:
    targetNamespaces:
    - ${NAMESPACE}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: deployment-validation-operator-config
    labels:
      name: deployment-validation-operator
  data:
    deployment-validation-operator-config.yaml: |-
      checks:
        # if doNotAutoAddDefaults is true, default checks are not automatically added.
        doNotAutoAddDefaults: false

        # addAllBuiltIn, if set, adds all built-in checks. This allows users to
        # explicitly opt-out of checks that are not relevant using Exclude.
        # Takes precedence over doNotAutoAddDefaults, if both are set.
        addAllBuiltIn: true

        exclude: ["access-to-create-pods", "access-to-secrets", "cluster-admin-role-binding", "default-service-account", "deprecated-service-account-field", "docker-sock", "drop-net-raw-capability", "env-var-secret", "exposed-services", "latest-tag", "mismatching-selector", "no-extensions-v1beta", "no-liveness-probe", "no-read-only-root-fs", "no-readiness-probe", "no-rolling-update-strategy", "privileged-ports", "read-secret-from-env-var", "required-annotation-email", "required-label-owner", "sensitive-host-mounts", "ssh-port", "unsafe-proc-mount", "use-namespace", "wildcard-in-rules", "writable-host-mount"]
- apiVersion: v1
  kind: Service
  metadata:
    name: deployment-validation-operator-metrics
    namespace: openshift-deployment-validation-operator
    labels:
      name: deployment-validation-operator
  spec:
    ports:
    - name: http-metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
    selector:
      name: deployment-validation-operator
parameters:
- name: IMAGE
  value: "quay.io/app-sre/deployment-validation-operator-catalog"
  displayName: Catalog image with the deployment-validation-operator
  description: the image of a catalog to deploy that contains the deployment-validation-operator
  required: true
- name: IMAGE_TAG
  value: "latest"
  displayName: deployment-validation-operator catalog version
  description: the version of the deployment-validation-operator catalog to deploy
  required: true
- name: NAMESPACE
  value: "deployment-validation-operator"
  displayName: namespace to deploy into
  description: the namespace to deploy into
  required: true
- name: CHANNEL
  value: "alpha"
  displayName: OLM subscription channel
  description: OLM subscription channel
  required: true
- name: NAMESPACE_IGNORE_PATTERN
  value: "^(openshift.*|kube-.*|default|dedicated-admin|redhat-.*|acm|addon-dba-operator|codeready-.*|prow)$"
  displayName: Namespace ignore pattern
  description: A golang regex to ignore checks from matching patterns
- name: SOURCE
  value: "deployment-validation-operator-catalog"
  displayName: Operator catalog source
  description: Catalog source that provides the operator
- name: SOURCE_NAMESPACE
  value: "deployment-validation-operator"
  displayName: Catalog namespace source
  description: Namespace containing the catalog source
- name: CATALOG_PUBLISHER
  value: "OperatorHub.io"
  displayName: Publisher of the catalog
  description: The name of the publisher of the catalog
