apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-validation-operator
  name: deployment-validation-operator
  annotations:
    ignore-check.kube-linter.io/minimum-three-replicas: "This deployment uses 1 pod as currently replicating does not replicate metric data causing installation issues"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-validation-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: deployment-validation-operator
        app: deployment-validation-operator
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - deployment-validation-operator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: quay.io/deployment-validation-operator/dv-operator:0.2.0
        imagePullPolicy: Always
        name: deployment-validation-operator
        args:
        - --config /config/deployment-validation-operator-config.yaml
        resources:
          requests:
            memory: "256Mi"
            cpu: "100n"
          limits:
            memory: "4Gi"
            cpu: "1"
        livenessProbe:
          tcpSocket:
            port: 8383
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8383
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAME
          value: "deployment-validation-operator"
        - name: NAMESPACE_IGNORE_PATTERN
          value: "openshift.*|kube-.+|default|dedicated-admin"
        - name: RESOURCES_PER_LIST_QUERY
          value: "5"
        - name: VALIDATION_CHECK_INTERVAL
          value: "2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: dvo-config
          mountPath: /config
        securityContext:
          readOnlyRootFilesystem: true
      volumes:
      - name: dvo-config
        configMap:
          optional: true
          name: deployment-validation-operator-config
      restartPolicy: Always
      serviceAccountName: deployment-validation-operator
      terminationGracePeriodSeconds: 30
